// Regenerates src/abi.ts from src/Rienda.abi.json (exported from forge: jq '.abi' out/Rienda.sol/Rienda.json).
import { readFileSync, writeFileSync } from "node:fs";

const abi = JSON.parse(readFileSync(new URL("../src/Rienda.abi.json", import.meta.url), "utf8"));
const out =
  "// GENERATED by `npm run gen:abi -w packages/sdk` from Rienda.abi.json. Do not edit by hand.\n" +
  `export const riendaAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;
writeFileSync(new URL("../src/abi.ts", import.meta.url), out);
